### ISSUE TITLE
Malformed yaml in `ds_env_studio_user_profile_v1.yaml` and `ds_env_studio_user_profile_v2.yaml`

### ISSUE THREAD

**Issue by Analect** [aws-samples/amazon-sagemaker-studio-secure-data-science-workshop#9]
**Describe the bug**
At the end of Lab1 when setting up Data Science Studio User Profile in AWS Service Catalog, it was failing on referencing the `ds_env_studio_user_profile_v1.yaml` from the S3 bucket, with an error that the YAML was malformed. It turns out I needed to add a second `- Fn::ImportValue:` between the two `!Sub` commands at the bottom here to get a valid template with `aws cloudformation validate-template --template-body file:///home/ec2-user/environment/amazon-sagemaker-studio-secure-data-science-workshop/cloudformation/ds_env_studio_user_profile_v1.yaml` ... and for me to ultimately be able to create the product on the console.

I believe a fix for `ds_env_studio_user_profile_v2.yaml` is required too.

```
SageMakerStudioUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId:
        Fn::ImportValue:
          !Sub 'ds-sagemaker-studio-${SharedServiceStackSetName}-domain-id'
      UserProfileName: !Ref StudioUserProfileName
      UserSettings:
        ExecutionRole: !GetAtt SageMakerExecRole.Arn
        SharingSettings:
          NotebookOutputOption: Disabled
        SecurityGroups:
          - Fn::ImportValue:
              !Sub 'ds-sagemaker-vpc-sg-${SharedServiceStackSetName}'
          - Fn::ImportValue:    
              !Sub 'ds-userprofile-sg-${SharedServiceStackSetName}'
```

**To Reproduce**
From Lab1 instructions:
Add **Data Science Studio User Profile Product**
1. Click Products
2. Click Upload new product
3. Enter a Product name of Data Science Studio User Profile
4. Optionally enter a Description like Creates a SageMaker Studio User Profile.
5. For Owner enter Data Science Administration Office
6. Click Use a CloudFormation template
7. For the CloudFormation template URL enter the HTTPS URL for template `ds_env_studio_user_profile_v1.yaml` from the S3 bucket to which CloudFormation templates for the workshop were uploaded earlier:
8. Visit [Amazon S3 console ](https://console.aws.amazon.com/s3) for the region, select the S3 bucket created earlier with name `secure-data-science-cloudformation-{RANDOM_NUMBER}-{REGION}`, go to folder `quickstart`.
From list of Objects, click on hyperlink for template `ds_env_studio_user_profile_v1.yaml`.

On attempt to create, there is an error in the console.

**Expected behavior**
No YAML malformed error.

**Screenshots**
![image](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/4063815/2e50f38c-d74e-425f-814a-3565a0af42ff)
